version: 2

updates:
  # Keep Github Actions dependencies up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Strategy production dependencies on main branch.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"
    open-pull-requests-limit: 100
    target-branch: "main"
    versioning-strategy: "lockfile-only"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"
    open-pull-requests-limit: 100
    target-branch: "main"
    versioning-strategy: "lockfile-only"

  # Strategy for development dependencies on main branch.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
      - dependency-type: "development"
    open-pull-requests-limit: 100
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
      - dependency-type: "development"
    open-pull-requests-limit: 100
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"
