test:app:
  script:
  - pwd
  - composer update
  - |
    cat > confg/config_db.php <<- EOM
    <?php
    class DB extends DBmysql {
      var $dbhost = 'localhost';
      var $dbuser  = 'glpi-testsuite';
      var $dbpassword= 'glpi-testsuite';
      var $dbdefault = 'glpi-testsuite';
    }
    ?>
    EOM
  - php tests/installGLPI.php --force
  - phpunit --verbose --debug
  - rm confg/config_db.php