test:app:
  script:
  - pwd
  - composer update --quiet
  - |
    cat > config/config_db.php << EOM
    <?php
    class DB extends DBmysql {
      var \$dbhost = 'localhost';
      var \$dbuser  = 'glpi-testsuite';
      var \$dbpassword= 'glpi-testsuite';
      var \$dbdefault = 'glpi-testsuite';
    }
    ?>
    EOM
  - php tests/installGLPI.php --force
  - phpunit --verbose --debug
  - rm config/config_db.php