language: php
sudo: required

services:
  - mysql

before_script:
  - phpenv config-rm xdebug.ini || true
  - ./tests/LDAP/ldap_run.sh
  - composer self-update
  - rm -f composer.lock
  - composer config --unset platform
  - composer install --optimize-autoloader
  - mysql -u root -e 'create database glpitest;'
  - bin/console glpi:database:install --config-dir=./tests --no-interaction --db-name=glpitest --db-user=root
  - ./tests/LDAP/ldap_fixtures.sh > /dev/null

script:
  - mysql -u root -e 'select version();'
  - composer testldap

matrix:
  include:
    - php: 5.6
      dist: trusty
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
    - php: 7.0
      dist: xenial
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
    - php: 7.1
      dist: xenial
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
    - php: 7.2
      dist: bionic
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
    - php: 7.3
      dist: bionic
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
    - php: 7.4
      dist: bionic
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
    - php: nightly
      dist: bionic
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - openldap
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "chat.freenode.org#glpi"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

#exclude old branches, without tests
branches:
  except:
    - /^0\..*$/
