language: php

env:
  - DB=mysql

before_script:
  - composer self-update
  - sed -e '/"php":/d' -i composer.json
  - rm -f composer.lock
  - composer install --optimize-autoloader
    #upstream patch, bt not yet part of the last release :( TODO: remove when upstream will include it.
  - patch -d vendor/guzzlehttp/guzzle/ -p1 < tools/guzzle-php72.patch
  - mysql -u root -e 'create database glpitest;'
  - php tools/cliinstall.php --db=glpitest --user=root --tests
  - php tools/cliupdate.php --config-dir=../tests |grep -q "No migration needed." || (echo "tools/cliupdate.php FAILED" && exit 1)
  - php -S localhost:8088 tests/router.php &>/dev/null &
  - phpenv config-add tests/enable-ldap.ini
  - sh tests/LDAP/load_ldap.sh
script:
  - mysql -u root -e 'select version();'
  - vendor/bin/atoum --debug -bf tests/bootstrap.php -d tests/units --no-cc -mcn 1
  - vendor/bin/atoum --debug -bf tests/bootstrap.php -d tests/api --no-cc -mcn 1
  - if [[ "$CS" == "true" ]]; then vendor/bin/phpcs -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ --ignore=/vendor/,/plugins/,/files/,/lib/,/config/,/tests/config ./; fi

#note: default maria version is 5.5 for all main php versions list exept nightly
matrix:
  include:
    - php: 5.6
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master

    - php: 5.6
      addons:
        mariadb: 10.0
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: 5.6
      addons:
        mariadb: 10.1
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: 7.0
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: 7.0
      addons:
        mariadb: 10.0
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: 7.1
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: 7.0
      addons:
        mariadb: 10.1
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: 7.1
      addons:
        mariadb: 10.0
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: 7.1
      env: CS=true
      addons:
        mariadb: 10.1
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: nightly
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
    - php: nightly
      addons:
        mariadb: 10.1
        apt:
          packages:
            - ldap-utils
            - slapd
        hosts:
          - ldap-master
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "chat.freenode.org#glpi"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

#exclude old branches, without tests
branches:
  except:
    - /^0\..*$/
