name: Bug Report
description: Create a report to help us improve GLPI (plugins issues are not handled here)
body:
  - type: markdown
    attributes:
      value: |

        Dear GLPI user.

        BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps:

        * We don't support community plugins. Contact directly their authors, or use [the community forum](https://forum.glpi-project.org).
        * For feature requests or enhancements, use the [suggest dedicated site](https://suggest.glpi-project.org). We check it very often.
        * Keep this tracker in ENGLISH. If you want support in your language, the [community forum](https://forum.glpi-project.org) is the best place.

        The GLPI team.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow hereinabove rules and [Contribution guide](https://github.com/glpi-project/glpi/blob/master/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our GLPI are you running?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. Find them in `*-error.log` files under `glpi/files/_log/`.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

        This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: Page(s) URL
      description: If applicable, page(s) URL where the bug happens.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. With this config...
        2. Go to...
        3. Scroll down to...
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Your GLPI setup (you can find it in Setup > General menu, System tab)
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: Add any other context about the problem here.
    validations:
      required: false
