version: '3.9'

services:
  php:
    container_name: "glpi-php-fpm"
    build:
      context: conf/php
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ..:/var/www/:rw
    depends_on:
      - db

  nginx:
    container_name: "glpi-nginx"
    build:
      context: ./conf/nginx
    networks:
      - default
    volumes:
      - ..:/var/www:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - "9090:80"

  db:
    container_name: "glpi-db"
    image: mariadb:10.7.3
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: glpi
      MARIADB_DATABASE: glpi
      MARIADB_USER: glpi
      MARIADB_PASSWORD: glpi
    ports:
      - "3306:3306"

volumes:
  glpi-src:
  mariadb-data:
